name: iOS Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Install dependencies
        run: |
          set -ex
          brew update
          brew install cocoapods || brew upgrade cocoapods
          sudo gem install fastlane -NV
          pod install

      - name: Decode credentials
        run: |
          set -ex
          echo "$CERTIFICATE_P12" | base64 --decode > cert.p12
          echo "$PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision
          echo "$APP_STORE_KEY" | base64 --decode > AuthKey.p8
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
          APP_STORE_KEY: ${{ secrets.APP_STORE_KEY }}

      - name: Set up code signing
        run: |
          set -ex
          security create-keychain -p github build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p github build.keychain
          security import cert.p12 -k build.keychain -P "${CERTIFICATE_PASSWORD}" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Build and Deploy with Fastlane
        run: |
          set -ex
          fastlane release
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY: ${{ secrets.APP_STORE_KEY }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
